{
  "name": "neo",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "start": "node ./[DOC-ROOT][MODULE-DIR]/tools/neo-cli.cjs",
    "deploy": "npm start -all",
    "preview": "vite preview"
  },
  "devDependencies": {
    "@inquirer/prompts": "^7.8.2",
    "@tailwindcss/vite": "^4.1.11",
    "@tailwindcss/forms": "^0.5.10",
    "@tailwindcss/typography": "^0.5.16",
    "@types/jquery": "^3.5.32",
    "tailwindcss": "^4.1.11",
    "typescript": "~5.8.3",
    "vite": "^7.1.3"
  }
}
