<?php

declare(strict_types=1);

namespace Drupal\Tests\neo_build\Unit;

use Drupal\Component\Serialization\Yaml;
use Drupal\neo_build\Generator\PhpstanGenerator;
use Drupal\neo_build\NeoBuildCollection;
use Drupal\Tests\UnitTestCase;
use PHPUnit\Framework\Attributes\Group;
use Symfony\Component\Console\Output\NullOutput;

/**
 * Tests the phpstan.neon artifact generator.
 *
 * The generator is handed the analysed extensions (name => path relative to
 * the app root) and the one environmental fact it cannot read from the
 * collection — whether phpstan/extension-installer is installed — and renders
 * the artifact the site's phpstan gate runs against. Two things here are the
 * whole reason the generator exists as a class: the include rule, which used
 * to produce a double include that made PHPStan refuse to run at all on any
 * site with the installer; and the path order, which must be stable so that
 * a regenerated file diffs by what changed and nothing else.
 */
#[Group('neo_build')]
class PhpstanGeneratorTest extends UnitTestCase {

  /**
   * Analysed extensions as the resolver hands them over, in resolver order.
   *
   * Deliberately not alphabetical: the generator must keep this order, not
   * impose its own.
   */
  protected const PATHS = [
    'neo' => 'modules/contrib/neo',
    'neo_alchemist_block' => 'modules/contrib/neo_alchemist/modules/neo_alchemist_block',
    'neo_alchemist' => 'modules/contrib/neo_alchemist',
    'front' => 'themes/front',
    'neo_build' => 'modules/contrib/neo_build',
    'customModules' => 'modules/custom',
  ];

  /**
   * Builds a collection rooted at a known project root and docroot.
   */
  protected function collection(): NeoBuildCollection {
    return new NeoBuildCollection(
      new NullOutput(),
      'wps.ddev.site',
      5173,
      TRUE,
      FALSE,
      '/var/www/html',
      'web',
      'modules/contrib/neo_build',
    );
  }

  /**
   * Renders the artifact and decodes it.
   *
   * @param bool $extensionInstallerInstalled
   *   Whether phpstan/extension-installer is installed.
   *
   * @return array
   *   The decoded artifact content.
   */
  protected function decoded(bool $extensionInstallerInstalled): array {
    $generator = new PhpstanGenerator(self::PATHS, $extensionInstallerInstalled);
    return Yaml::decode($generator->generate($this->collection())->getContent());
  }

  /**
   * Extension.neon is included only when the installer is absent.
   *
   * With phpstan/extension-installer present the installer already registers
   * phpstan-drupal's extension.neon; including it again is the double include
   * PHPStan aborts on. With the installer absent, the include is what gives
   * PHPStan its Drupal knowledge, so it stays.
   */
  public function testIncludesExtensionNeonOnlyWhenTheInstallerIsAbsent(): void {
    $without = $this->decoded(FALSE);
    $this->assertSame(['vendor/mglaman/phpstan-drupal/extension.neon'], $without['includes']);

    $with = $this->decoded(TRUE);
    $this->assertArrayNotHasKey('includes', $with);
    $this->assertSame(['parameters'], array_keys($with));
  }

  /**
   * Level, file extensions, ignore patterns and path order are as specified.
   */
  public function testEmitsLevelExtensionsIgnoresAndPathsInOrder(): void {
    $artifact = (new PhpstanGenerator(self::PATHS, TRUE))->generate($this->collection());

    $this->assertSame('/var/www/html/phpstan.neon', $artifact->getDestination());
    $this->assertStringStartsWith("# This file is auto-generated by Neo\n", $artifact->getContent());

    $parameters = Yaml::decode($artifact->getContent())['parameters'];
    $this->assertSame(['level', 'paths', 'fileExtensions', 'ignoreErrors'], array_keys($parameters));
    $this->assertSame(1, $parameters['level']);
    $this->assertSame(['php', 'module', 'inc', 'install', 'theme'], $parameters['fileExtensions']);
    $this->assertSame([
      '#^Unsafe usage of new static#',
      '#Drupal calls should be avoided in classes, use dependency injection instead#',
      '#^Plugin definitions cannot be altered.#',
      '#^Class .* extends @internal class#',
    ], $parameters['ignoreErrors']);
    $this->assertSame([
      './web/modules/contrib/neo',
      './web/modules/contrib/neo_alchemist/modules/neo_alchemist_block',
      './web/modules/contrib/neo_alchemist',
      './web/themes/front',
      './web/modules/contrib/neo_build',
      './web/modules/custom',
    ], $parameters['paths']);
  }

  /**
   * Excluded paths are rendered under excludePaths, after the paths.
   *
   * With nothing excluded the key is omitted entirely — the test above pins
   * that key set — so a site with no unresolvable nested extension gets the
   * same file it always got.
   */
  public function testRendersExcludePathsWhenThereAreAny(): void {
    $generator = new PhpstanGenerator(self::PATHS, TRUE, [
      'neo_build_entity_print' => 'modules/contrib/neo_build/modules/neo_build_entity_print',
    ]);

    $parameters = Yaml::decode($generator->generate($this->collection())->getContent())['parameters'];
    $this->assertSame(['level', 'paths', 'excludePaths', 'fileExtensions', 'ignoreErrors'], array_keys($parameters));
    $this->assertSame(['./web/modules/contrib/neo_build/modules/neo_build_entity_print'], $parameters['excludePaths']);
  }

}
