<?php

declare(strict_types=1);

namespace Drupal\Tests\neo_build\Unit;

use Drupal\neo_build\Generator\TailwindCssGenerator;
use Drupal\neo_build\NeoBuildCollection;
use Drupal\neo_build\Generator\TailwindStylesheet;
use Drupal\Tests\UnitTestCase;
use PHPUnit\Framework\Attributes\Group;

/**
 * Tests the tailwind.neo.css artifact generator.
 *
 * The stylesheet carries everything the partition rule assigns to CSS —
 * imports, sources, `--` theme variables, base, components, utilities and
 * variants — rendered by TailwindStylesheet behind a header and the @plugin
 * line that points at the module's Tailwind plugin. It lands beside the
 * scope's primary file; with no primary file there is no artifact, and the
 * caller gets a reason rather than a stray file at the docroot root.
 */
#[Group('neo_build')]
class TailwindCssGeneratorTest extends UnitTestCase {

  /**
   * The header and plugin line every CSS artifact begins with.
   */
  protected const HEADER = "/*\n * NEO Tailwind CSS\n * Generated by Neo Build. Do NOT edit this file directly.\n */\n\n/* NEO Plugin */\n@plugin \"/var/www/html/web/modules/contrib/neo_build/tools/neo-tailwind-plugin.ts\";\n\n";

  /**
   * Builds a collection rooted at a known project root and docroot.
   */
  protected function collection(): NeoBuildCollection {
    return new NeoBuildCollection(
      'wps.ddev.site',
      5173,
      TRUE,
      FALSE,
      '/var/www/html',
      'web',
      'modules/contrib/neo_build',
    );
  }

  /**
   * Builds a collection with a primary file and one of everything CSS owns.
   */
  protected function populated(): NeoBuildCollection {
    $collection = $this->collection();
    $collection->setPrimaryRoot('themes/front');
    $collection->setPrimaryFile('themes/front/src/css/main.css');
    $collection->addTailwindImport('neo:base', 'modules/contrib/neo/src/css/base.css');
    $collection->addTailwindSource('front:Files', 'themes/front/src/**/*.twig');
    $collection->addTailwindThemeItem('--color-brand', 'red');
    $collection->addTailwindTheme(['extend' => ['colors' => ['brand' => 'var(--color-brand)']]]);
    $collection->addTailwindBase(['html' => ['color' => 'red'], '--base-gap' => '1rem']);
    $collection->addTailwindComponents(['.card' => ['padding' => '1rem'], '--card-pad' => '2rem']);
    $collection->addTailwindUtility('.text-balance', ['text-wrap' => 'balance']);
    $collection->addTailwindVariants(['hocus' => ['&:hover', '&:focus']]);
    return $collection;
  }

  /**
   * The header and plugin line come first; the stylesheet body follows.
   *
   * The body is pinned against TailwindStylesheet fed the same inputs in the
   * same order, so the generator's routing is exactly the routing the command
   * used to do.
   */
  public function testRendersHeaderAndPluginLineAheadOfTheStylesheetBody(): void {
    $artifact = (new TailwindCssGenerator())->generate($this->populated());

    $this->assertSame('/var/www/html/web/themes/front/src/css/tailwind.neo.css', $artifact->getDestination());
    $this->assertStringStartsWith(self::HEADER, $artifact->getContent());

    $css = new TailwindStylesheet();
    $css->addImports(['/var/www/html/web/modules/contrib/neo/src/css/base.css']);
    $css->addSources(['/var/www/html/web/themes/front/src/**/*.twig']);
    $css->addCssVariable('--color-brand', 'red');
    $css->addRule('html', ['color' => 'red'], 'base');
    $css->addCssVariable('--base-gap', '1rem', 'base');
    $css->addRule('.card', ['padding' => '1rem'], 'components');
    $css->addCssVariable('--card-pad', '2rem', 'components');
    $css->addUtility('.text-balance', ['text-wrap' => 'balance']);
    $css->addVariant('hocus', ['&:hover', '&:focus']);
    $this->assertSame(self::HEADER . $css->toCss(), $artifact->getContent());
  }

  /**
   * Everything CSS owns reaches the stylesheet, and the collection keeps it.
   */
  public function testRoutesVariablesBaseComponentsUtilitiesAndVariantsWithoutEmptyingTheCollection(): void {
    $collection = $this->populated();

    $content = (new TailwindCssGenerator())->generate($collection)->getContent();

    foreach (['--color-brand', '--base-gap', 'html', '--card-pad', '.card', 'text-balance', 'hocus'] as $needle) {
      $this->assertStringContainsString($needle, $content);
    }
    $this->assertSame(['neo:base' => 'modules/contrib/neo/src/css/base.css'], $collection->getTailwindImports());
    $this->assertSame(['front:Files' => 'themes/front/src/**/*.twig'], $collection->getTailwindSources());
    $this->assertSame('red', $collection->getTailwindTheme()['--color-brand']);
    $this->assertArrayHasKey('html', $collection->getTailwindBase());
    $this->assertArrayHasKey('.card', $collection->getTailwindComponents());
    $this->assertArrayHasKey('.text-balance', $collection->getTailwindUtilities());
    $this->assertArrayHasKey('hocus', $collection->getTailwindVariants());
  }

  /**
   * No primary file: no artifact, and a reason the caller can print.
   */
  public function testProducesNoArtifactAndReportsTheMissingPrimaryFile(): void {
    $collection = $this->collection();
    $this->assertNull($collection->getPrimaryFile());

    $this->assertNull((new TailwindCssGenerator())->generate($collection));
    $this->assertStringContainsString('primary', TailwindCssGenerator::MISSING_PRIMARY_FILE_NOTICE);
  }

}
