<?php

declare(strict_types=1);

namespace Drupal\Tests\neo_build\Unit;

use Drupal\neo_build\Generator\TailwindCssGenerator;
use Drupal\neo_build\NeoBuildCollection;
use Drupal\neo_build\Generator\TailwindStylesheet;
use Drupal\Tests\UnitTestCase;
use PHPUnit\Framework\Attributes\Group;

/**
 * Tests the tailwind.neo.css artifact generator.
 *
 * The stylesheet carries everything the partition rule assigns to CSS —
 * imports, sources, `--` theme variables, components, utilities and
 * variants — rendered by TailwindStylesheet behind a header and the @plugin
 * line that points at the module's Tailwind plugin. It lands beside the
 * scope's primary file; with no primary file there is no artifact, and the
 * caller gets a reason rather than a stray file at the docroot root.
 */
#[Group('neo_build')]
class TailwindCssGeneratorTest extends UnitTestCase {

  /**
   * The header and plugin line every CSS artifact begins with.
   */
  protected const HEADER = "/*\n * NEO Tailwind CSS\n * Generated by Neo Build. Do NOT edit this file directly.\n */\n\n/* NEO Plugin */\n@plugin \"/var/www/html/web/modules/contrib/neo_build/tools/neo-tailwind-plugin.ts\";\n\n";

  /**
   * Builds a collection rooted at a known project root and docroot.
   */
  protected function collection(): NeoBuildCollection {
    return new NeoBuildCollection(
      5173,
      FALSE,
      '/var/www/html',
      'web',
      'modules/contrib/neo_build',
    );
  }

  /**
   * Builds a collection with a primary file and one of everything CSS owns.
   */
  protected function populated(): NeoBuildCollection {
    $collection = $this->collection();
    $collection->setPrimaryRoot('themes/front');
    $collection->setPrimaryFile('themes/front/src/css/main.css');
    $collection->addTailwindImport('neo:base', 'modules/contrib/neo/src/css/base.css');
    $collection->addTailwindSource('front:Files', 'themes/front/src/**/*.twig');
    $collection->addTailwindThemeItem('--color-brand', 'red');
    $collection->addTailwindTheme(['extend' => ['colors' => ['brand' => 'var(--color-brand)']]]);
    $collection->addTailwindComponents(['.card' => ['padding' => '1rem']]);
    $collection->addTailwindUtility('.text-balance', ['text-wrap' => 'balance']);
    $collection->addTailwindVariants(['hocus' => ['&:hover', '&:focus']]);
    return $collection;
  }

  /**
   * The header and plugin line come first; the stylesheet body follows.
   *
   * The body is pinned against TailwindStylesheet fed the same inputs in the
   * same order, so the generator's routing is exactly the routing the command
   * used to do.
   */
  public function testRendersHeaderAndPluginLineAheadOfTheStylesheetBody(): void {
    $artifact = (new TailwindCssGenerator())->generate($this->populated());

    $this->assertSame('/var/www/html/web/themes/front/src/css/tailwind.neo.css', $artifact->getDestination());
    $this->assertStringStartsWith(self::HEADER, $artifact->getContent());

    $css = new TailwindStylesheet();
    $css->addImports(['/var/www/html/web/modules/contrib/neo/src/css/base.css']);
    $css->addSources(['/var/www/html/web/themes/front/src/**/*.twig']);
    $css->addCssVariable('--color-brand', 'red');
    $css->addRule('.card', ['padding' => '1rem'], 'components');
    $css->addUtility('.text-balance', ['text-wrap' => 'balance']);
    $css->addVariant('hocus', ['&:hover', '&:focus']);
    $this->assertSame(self::HEADER . $css->toCss(), $artifact->getContent());
  }

  /**
   * Everything CSS owns reaches the stylesheet, and the collection keeps it.
   */
  public function testRoutesVariablesComponentsUtilitiesAndVariantsWithoutEmptyingTheCollection(): void {
    $collection = $this->populated();

    $content = (new TailwindCssGenerator())->generate($collection)->getContent();

    foreach (['--color-brand', '.card', 'text-balance', 'hocus'] as $needle) {
      $this->assertStringContainsString($needle, $content);
    }
    $this->assertSame(['neo:base' => 'modules/contrib/neo/src/css/base.css'], $collection->getTailwindImports());
    $this->assertSame(['front:Files' => 'themes/front/src/**/*.twig'], $collection->getTailwindSources());
    $this->assertSame('red', $collection->getTailwindTheme()['--color-brand']);
    $this->assertArrayHasKey('.card', $collection->getTailwindComponents());
    $this->assertArrayHasKey('.text-balance', $collection->getTailwindUtilities());
    $this->assertArrayHasKey('hocus', $collection->getTailwindVariants());
  }

  /**
   * The components layer holds rules only, never a bare declaration.
   *
   * A custom property routed into a layer would be emitted at the layer's own
   * indentation, outside any rule — `@layer components { --card-pad: 2rem; }`,
   * which is not valid CSS. The generator no longer has a branch that can do
   * it: `--` keys reach the stylesheet through the theme loop and land in
   * `@theme`, and everything in component data becomes a rule.
   *
   * The assertion is on indentation because that is what distinguishes the two
   * cases: inside the block, a rule's selector opens at one level and its
   * declarations sit at two, so a declaration at one level is a bare one.
   */
  public function testEmitsNoBareDeclarationInsideTheComponentsLayer(): void {
    $content = (new TailwindCssGenerator())->generate($this->populated())->getContent();

    $open = strpos($content, "@layer components {\n");
    $this->assertNotFalse($open, 'the artifact has a components layer to check');
    $block = substr($content, $open, strpos($content, "\n}\n", $open) - $open);

    foreach (explode("\n", $block) as $line) {
      $this->assertDoesNotMatchRegularExpression(
        '/^  [^ }].*:.*;$/',
        $line,
        'a declaration sits directly inside @layer components: ' . $line,
      );
    }
  }

  /**
   * No primary file: no artifact, and a reason the caller can print.
   */
  public function testProducesNoArtifactAndReportsTheMissingPrimaryFile(): void {
    $collection = $this->collection();
    $this->assertNull($collection->getPrimaryFile());

    $this->assertNull((new TailwindCssGenerator())->generate($collection));
    $this->assertStringContainsString('primary', TailwindCssGenerator::MISSING_PRIMARY_FILE_NOTICE);
  }

  /**
   * Builds a collection with a primary file and one section's data.
   *
   * The entry arrives exactly as an extension contributes it, so a list-shaped
   * contribution keeps the integer key `foreach` will yield.
   *
   * @param string $section
   *   The section the data belongs to: 'components' or 'utilities'.
   * @param array $data
   *   The section data.
   *
   * @return \Drupal\neo_build\NeoBuildCollection
   *   The collection.
   */
  protected function withEntry(string $section, array $data): NeoBuildCollection {
    $collection = $this->collection();
    $collection->setPrimaryRoot('themes/front');
    $collection->setPrimaryFile('themes/front/src/css/main.css');

    if ($section === 'components') {
      $collection->addTailwindComponents($data);
    }
    else {
      $collection->addTailwindUtilities($data);
    }

    return $collection;
  }

  /**
   * Generates, and returns the refusal the generator threw.
   *
   * @param \Drupal\neo_build\NeoBuildCollection $collection
   *   The collection to generate from.
   *
   * @return string
   *   The refusal message.
   */
  protected function refusal(NeoBuildCollection $collection): string {
    try {
      (new TailwindCssGenerator())->generate($collection);
    }
    catch (\InvalidArgumentException $e) {
      return $e->getMessage();
    }

    $this->fail('the generator accepted an entry that breaks the selector-key rule');
  }

  /**
   * A `--` key in component data is refused, not routed.
   *
   * Up to 1.0.65 it was recognised and forwarded to addCssVariable(). The
   * branch is gone, because a custom property in selector position would
   * otherwise emit a bare declaration inside `@layer components`. The refusal
   * is what the removal left owing.
   */
  public function testRefusesCustomPropertyKeysInComponentData(): void {
    $message = $this->refusal($this->withEntry('components', ['--card-pad' => '2rem']));

    $this->assertStringContainsString('components', $message);
    $this->assertStringContainsString('"--card-pad"', $message);
    $this->assertStringContainsString('selector', $message);
    $this->assertStringContainsString('declarations', $message);
    $this->assertStringContainsString('theme:', $message);
  }

  /**
   * A `--` key is refused on the key alone, whatever its value.
   *
   * The shape that passed every type check: with an array value it raised no
   * TypeError at all and quietly emitted `--card-pad { … }` as a selector into
   * `@layer components`.
   */
  public function testRefusesCustomPropertyKeysGivenAnArrayValueInComponentData(): void {
    $message = $this->refusal($this->withEntry('components', ['--card-pad' => ['padding' => '2rem']]));

    $this->assertStringContainsString('components', $message);
    $this->assertStringContainsString('"--card-pad"', $message);
    $this->assertStringContainsString('selector', $message);
  }

  /**
   * A non-array value under an ordinary selector is refused.
   *
   * The identical TypeError with no `--` in sight: a utility string written
   * where a declarations array belongs.
   */
  public function testRefusesNonArrayValuesUnderOrdinarySelectors(): void {
    $message = $this->refusal($this->withEntry('components', ['.card' => 'text-center']));

    $this->assertStringContainsString('components', $message);
    $this->assertStringContainsString('".card"', $message);
    $this->assertStringContainsString('array of declarations', $message);
  }

  /**
   * A list-shaped contribution is refused on its integer key.
   *
   * This one fails one argument earlier than the rest — on `$selector` rather
   * than `$properties` — and the entry it names has no selector to report.
   */
  public function testRefusesNonStringKeysFromListShapedContributions(): void {
    $message = $this->refusal($this->withEntry('components', [['padding' => '1rem']]));

    $this->assertStringContainsString('components', $message);
    $this->assertStringContainsString('"0"', $message);
    $this->assertStringContainsString('selector', $message);
  }

  /**
   * The same four shapes are refused in utility data, named as utilities.
   *
   * One rule, both loops. The section in the message is the section the entry
   * arrived in, which is the only thing that tells a reader which half of an
   * info file to open.
   */
  public function testRefusesTheSameFourShapesInUtilityData(): void {
    $entries = [
      ['--card-pad' => '2rem'],
      ['--card-pad' => ['padding' => '2rem']],
      ['.card' => 'text-center'],
      [['padding' => '1rem']],
    ];

    foreach ($entries as $entry) {
      $message = $this->refusal($this->withEntry('utilities', $entry));

      $this->assertStringContainsString('utilities', $message);
      $this->assertStringNotContainsString('components', $message);
    }
  }

  /**
   * Custom properties inside a rule's declarations are untouched.
   *
   * Modelled on neo_color's prose contribution — a four-part scheme selector
   * mapped to fourteen `--tw-prose-*` declarations — because that is the live
   * shape on every site, and the one a guard that walked into the declarations
   * array would break under every scheme. The rule is about the key position.
   */
  public function testRendersCustomPropertiesInsideComponentRulesUnchanged(): void {
    $selector = implode(', ', [
      '[class^="scheme-"] .prose',
      '[class*=" scheme-"] .prose',
      '[class^="scheme-"].prose',
      '[class*=" scheme-"].prose',
    ]);
    $text = 'var(--text-color-default)';
    $border = 'var(--color-border-default)';
    $muted = fn (int $pct) => "color-mix(in oklab, var(--text-color-default) {$pct}%, transparent)";
    $prose = [
      '--tw-prose-body' => $text . ' !important',
      '--tw-prose-headings' => $text . ' !important',
      '--tw-prose-lead' => $muted(80) . ' !important',
      '--tw-prose-links' => 'var(--link-color, var(--text-color-default)) !important',
      '--tw-prose-bold' => $text . ' !important',
      '--tw-prose-counters' => $muted(70) . ' !important',
      '--tw-prose-bullets' => $muted(45) . ' !important',
      '--tw-prose-hr' => $border . ' !important',
      '--tw-prose-quotes' => $text . ' !important',
      '--tw-prose-quote-borders' => $border . ' !important',
      '--tw-prose-captions' => $muted(70) . ' !important',
      '--tw-prose-code' => $text . ' !important',
      '--tw-prose-th-borders' => $border . ' !important',
      '--tw-prose-td-borders' => $border . ' !important',
    ];

    $content = (new TailwindCssGenerator())->generate($this->withEntry('components', [$selector => $prose]))->getContent();

    $css = new TailwindStylesheet();
    $css->addRule($selector, $prose, 'components');
    $this->assertSame(self::HEADER . $css->toCss(), $content);
    $this->assertStringContainsString('--tw-prose-body: var(--text-color-default) !important;', $content);
  }

}
