<?php

declare(strict_types=1);

namespace Drupal\neo_build\Generator;

use Composer\InstalledVersions;
use Drupal\Component\Serialization\Yaml;
use Drupal\neo_build\NeoBuildCollection;

/**
 * Generates phpstan.neon, the project's PHPStan configuration.
 *
 * The analysed paths come from the analysed-extension resolver and are emitted
 * relative to the project root, in the resolver's order — stable, so a
 * regenerated file diffs by what changed and nothing else. Level, file
 * extensions and the ignore patterns are fixed.
 *
 * phpstan-drupal's extension.neon is included only when
 * phpstan/extension-installer is absent. The installer registers that file
 * itself, and PHPStan refuses to run when a file is included twice — which is
 * exactly what the old unconditional include did on every site with the
 * installer. Whether the installer is present is handed to the constructor
 * rather than detected here, so a test can set it either way; callers detect
 * it with the static helper.
 */
final class PhpstanGenerator implements ArtifactGeneratorInterface {

  /**
   * The artifact's file name, relative to the project root.
   */
  public const FILENAME = 'phpstan.neon';

  /**
   * The include phpstan/extension-installer would otherwise register itself.
   */
  public const EXTENSION_NEON = 'vendor/mglaman/phpstan-drupal/extension.neon';

  /**
   * The Composer package whose presence makes that include a double include.
   */
  public const EXTENSION_INSTALLER = 'phpstan/extension-installer';

  /**
   * Constructs a PhpstanGenerator.
   *
   * @param array<string, string> $analysedExtensions
   *   Extension paths relative to the app root, keyed by name, in the order
   *   they are to be emitted.
   * @param bool $extensionInstallerInstalled
   *   Whether phpstan/extension-installer is installed.
   */
  public function __construct(
    private readonly array $analysedExtensions,
    private readonly bool $extensionInstallerInstalled,
  ) {}

  /**
   * Detects whether phpstan/extension-installer is installed.
   *
   * Asks Composer's runtime API, which reads the autoloader's own installed
   * package list — the same vendor directory PHPStan will run from.
   *
   * @return bool
   *   TRUE when the installer is installed.
   */
  public static function extensionInstallerInstalled(): bool {
    return class_exists(InstalledVersions::class)
      && InstalledVersions::isInstalled(self::EXTENSION_INSTALLER);
  }

  /**
   * {@inheritdoc}
   */
  public function generate(NeoBuildCollection $collection): ?Artifact {
    $relativeRoot = $collection->getRelativeRoot();
    $data = [
      'parameters' => [
        'level' => 1,
        'paths' => array_values(array_map(
          fn (string $path): string => $relativeRoot . $path,
          $this->analysedExtensions,
        )),
        'fileExtensions' => ['php', 'module', 'inc', 'install', 'theme'],
        'ignoreErrors' => [
          '#^Unsafe usage of new static#',
          '#Drupal calls should be avoided in classes, use dependency injection instead#',
          '#^Plugin definitions cannot be altered.#',
          '#^Class .* extends @internal class#',
        ],
      ],
    ];
    if (!$this->extensionInstallerInstalled) {
      $data['includes'] = [self::EXTENSION_NEON];
    }

    return new Artifact(
      $collection->getRoot() . self::FILENAME,
      "# This file is auto-generated by Neo\n" . Yaml::encode($data),
    );
  }

}
