<?php

declare(strict_types=1);

namespace Drupal\neo_build\Generator;

use Drupal\neo_build\NeoBuildCollection;

/**
 * Generates tailwind.neo.css, the stylesheet Tailwind compiles for a scope.
 *
 * The artifact lands beside the scope's primary file — the CSS entrypoint that
 * imports "tailwindcss" — and carries everything the partition rule assigns
 * to CSS: the imports and sources, the `--` theme variables, the component
 * rules, the utilities and the variants, rendered by
 * TailwindStylesheet behind a header and the @plugin line that points at the
 * module's Tailwind plugin.
 *
 * With no primary file there is nothing to write beside, so there is no
 * artifact: the generator returns NULL and the caller prints
 * MISSING_PRIMARY_FILE_NOTICE. The command used to write the file at the
 * docroot root in that case, silently.
 */
final class TailwindCssGenerator implements ArtifactGeneratorInterface {

  /**
   * The artifact's file name, written beside the primary file.
   */
  public const FILENAME = 'tailwind.neo.css';

  /**
   * What the caller says when there is no primary file to write beside.
   */
  public const MISSING_PRIMARY_FILE_NOTICE = 'No primary CSS file in this scope (one that imports "tailwindcss"): tailwind.neo.css was not written.';

  /**
   * {@inheritdoc}
   */
  public function generate(NeoBuildCollection $collection): ?Artifact {
    $primaryFile = $collection->getPrimaryFile();
    if ($primaryFile === NULL || $primaryFile === '') {
      return NULL;
    }

    $root = $collection->getRoot();
    $docRoot = $collection->getDocRoot();
    $absolute = fn (string $path): string => $root . $docRoot . $path;
    $pluginPath = $absolute($collection->getNeoRoot() . 'tools/neo-tailwind-plugin.ts');

    $css = new TailwindStylesheet();
    $css->addImports(array_map($absolute, $collection->getTailwindImports()));
    $css->addSources(array_map($absolute, $collection->getTailwindSources()));

    // CSS variables in the theme go to the stylesheet's theme layer; the rest
    // of the theme is the neo.json generator's, for the Tailwind plugin.
    foreach ($collection->getTailwindTheme() as $key => $value) {
      if (str_starts_with($key, '--') && is_string($value)) {
        $css->addCssVariable($key, $value);
      }
    }
    foreach ($collection->getTailwindComponents() as $key => $value) {
      if (str_starts_with($key, '--') && is_string($value)) {
        $css->addCssVariable($key, $value, 'components');
      }
      else {
        $css->addRule($key, $value, 'components');
      }
    }
    foreach ($collection->getTailwindUtilities() as $key => $value) {
      $css->addUtility($key, $value);
    }
    foreach ($collection->getTailwindVariants() as $name => $selectors) {
      $css->addVariant($name, $selectors);
    }

    $output = "/*\n";
    $output .= " * NEO Tailwind CSS\n";
    $output .= " * Generated by Neo Build. Do NOT edit this file directly.\n";
    $output .= " */\n\n";
    $output .= "/* NEO Plugin */\n";
    $output .= "@plugin \"$pluginPath\";\n\n";
    $output .= $css->toCss();

    return new Artifact($absolute(dirname($primaryFile) . '/' . self::FILENAME), $output);
  }

}
