<?php

declare(strict_types=1);

namespace Drupal\neo_build\Generator;

use Drupal\neo_build\NeoBuildCollection;

/**
 * Generates tailwind.neo.css, the stylesheet Tailwind compiles for a scope.
 *
 * The artifact lands beside the scope's primary file — the CSS entrypoint that
 * imports "tailwindcss" — and carries everything the partition rule assigns
 * to CSS: the imports and sources, the `--` theme variables, the component
 * rules, the utilities and the variants, rendered by
 * TailwindStylesheet behind a header and the @plugin line that points at the
 * module's Tailwind plugin.
 *
 * With no primary file there is nothing to write beside, so there is no
 * artifact: the generator returns NULL and the caller prints
 * MISSING_PRIMARY_FILE_NOTICE. The command used to write the file at the
 * docroot root in that case, silently.
 */
final class TailwindCssGenerator implements ArtifactGeneratorInterface {

  /**
   * The artifact's file name, written beside the primary file.
   */
  public const FILENAME = 'tailwind.neo.css';

  /**
   * What the caller says when there is no primary file to write beside.
   */
  public const MISSING_PRIMARY_FILE_NOTICE = 'No primary CSS file in this scope (one that imports "tailwindcss"): tailwind.neo.css was not written.';

  /**
   * {@inheritdoc}
   */
  public function generate(NeoBuildCollection $collection): ?Artifact {
    $primaryFile = $collection->getPrimaryFile();
    if ($primaryFile === NULL || $primaryFile === '') {
      return NULL;
    }

    $root = $collection->getRoot();
    $docRoot = $collection->getDocRoot();
    $absolute = fn (string $path): string => $root . $docRoot . $path;
    $pluginPath = $absolute($collection->getNeoRoot() . 'tools/neo-tailwind-plugin.ts');

    $css = new TailwindStylesheet();
    $css->addImports(array_map($absolute, $collection->getTailwindImports()));
    $css->addSources(array_map($absolute, $collection->getTailwindSources()));

    // CSS variables in the theme go to the stylesheet's theme layer; the rest
    // of the theme is the neo.json generator's, for the Tailwind plugin.
    foreach ($collection->getTailwindTheme() as $key => $value) {
      if (str_starts_with($key, '--') && is_string($value)) {
        $css->addCssVariable($key, $value);
      }
    }
    // Component data is rules only. A `--` key here would have to be emitted
    // as a bare declaration inside `@layer components`, which is not valid
    // CSS; the loop above reads the theme section, so a `--` key arriving in
    // component data is routed nowhere at all, and is refused below.
    foreach ($collection->getTailwindComponents() as $key => $value) {
      self::assertSelectorKey('components', $key, $value);
      $css->addRule($key, $value, 'components');
    }
    foreach ($collection->getTailwindUtilities() as $key => $value) {
      self::assertSelectorKey('utilities', $key, $value);
      $css->addUtility($key, $value);
    }
    foreach ($collection->getTailwindVariants() as $name => $selectors) {
      $css->addVariant($name, $selectors);
    }

    $output = "/*\n";
    $output .= " * NEO Tailwind CSS\n";
    $output .= " * Generated by Neo Build. Do NOT edit this file directly.\n";
    $output .= " */\n\n";
    $output .= "/* NEO Plugin */\n";
    $output .= "@plugin \"$pluginPath\";\n\n";
    $output .= $css->toCss();

    return new Artifact($absolute(dirname($primaryFile) . '/' . self::FILENAME), $output);
  }

  /**
   * Asserts one component or utility entry against the selector-key rule.
   *
   * The rule: an entry is a **string** key naming a CSS selector, mapped to an
   * **array** of declarations. Three shapes break it, and each was a fatal or
   * a silent miss before this gate existed — a non-string key from a
   * list-shaped contribution, a `--` key naming a custom property rather than
   * a selector, and a value that is not an array.
   *
   * Nothing **inside** the declarations array is inspected here. Custom
   * properties are legal there and illegal in key position: neo_color
   * contributes fourteen `--tw-prose-*` declarations in one entry on every
   * site, and a guard that walked into the array would break prose styling
   * under every scheme. The declarations themselves are
   * TailwindStylesheet::assertFlatDeclarations()'s business.
   *
   * The refusal does not name the extension, deliberately. The generators run
   * on the merged collection, where provenance is gone —
   * NeoBuildCollection::addTailwindComponents() takes no id — so the key is
   * what finds the culprit, and it is a literal string to grep for.
   *
   * @param string $section
   *   The section the entry arrived in: 'components' or 'utilities'. Named in
   *   the message because it says which half of an info file to open.
   * @param mixed $key
   *   The entry's key, exactly as it arrived.
   * @param mixed $value
   *   The entry's value, exactly as it arrived.
   *
   * @throws \InvalidArgumentException
   *   If the entry breaks the selector-key rule. Prepare is a fatal step, so
   *   this ends the build with a failure report rather than warning and
   *   dropping the entry.
   */
  private static function assertSelectorKey(string $section, mixed $key, mixed $value): void {
    if (!is_string($key)) {
      throw new \InvalidArgumentException(sprintf(
        'Tailwind %s data has an entry keyed "%s", which is not a string: an entry is a CSS selector mapped to an array of declarations. This is a list-shaped contribution; give the entry a selector.',
        $section,
        (string) $key,
      ));
    }

    if (str_starts_with($key, '--')) {
      throw new \InvalidArgumentException(sprintf(
        'Tailwind %s data has "%s" in selector position: an entry is a CSS selector mapped to an array of declarations, and "%s" names a custom property. Move it into a rule\'s declarations, or into the extension\'s `theme:` section. The key is a literal string: grep for it to find the extension that contributes it.',
        $section,
        $key,
        $key,
      ));
    }

    if (!is_array($value)) {
      throw new \InvalidArgumentException(sprintf(
        'Tailwind %s data gives "%s" a value of type %s: an entry is a CSS selector mapped to an array of declarations. Give "%s" an array of declarations. The key is a literal string: grep for it to find the extension that contributes it.',
        $section,
        $key,
        get_debug_type($value),
        $key,
      ));
    }
  }

}
